permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: linlinjava
  email: linlinjavaer@gmail.com
  github: http://github.com/linlinjava

# 站点信息
title: linlinjava的博客 
description: Thinking, Learning & Coding
url: https://linlinjava.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/gin_ta_ma.gif
favicon: /public/img/gin_ta_ma.gif


# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Git
  - Java

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
